### ISSUE TITLE
docs: "Portable; if vcsh is not installed on a machine, just copy the one POSIX script over"

### ISSUE THREAD

**Issue by RichiH** [RichiH/vcsh#73] opened 2013-08-01 09:34 UTC

**Comment by alerque** [comment] 2021-04-05 04:29
Closing this as a duplicate of #202. I definitely don't want to document this as a feature right now because it might not be true much longer. If I get my way with a configure/build system this might not be *quite* true any more (I'll list that as a downside in notes on the PR for review). It would work between very similar systems (i.e. `scp`ing the script from one GNU system to another or or one BSD to another would probably work, but `scp`ing my script from an Arch Linux box to a Windows or macOS machine might fail because the paths to dependencies that were discovered at compile time instead of run time could be different).

On the other hand a 'portable' or bootstrappable variant might still be something that could be explicitly built or otherwise arranged for, so tracking this on the other issue makes sense to me.

**Closed by alerque** 2021-04-05 04:29 UTC
