### ISSUE TITLE
Fail cloning when the remote repository does not exist

### ISSUE THREAD

**Issue by harendra-kumar** [RichiH/vcsh#209] opened 2016-06-22 00:55 UTC
While cloning, before we initialize the local repo we should first check whether the remote repository exists or not. I made a mistake while typing the local repo path when cloning and the cloning proceeded creating a repository with empty contents, not failing at any step. It only failed on a subsequent pull command. This can be avoided if we check right in the beginning using `git ls-remote -h <path>` and fail the clone if the repo does not exist.

**Comment by alerque** [comment] 2021-04-02 09:28
This is roughly a duplicate of #161 and should be fixed by the same solution proposed in #282.

**Closed** 2021-04-02 13:30 UTC
Labels: enhancement
